apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-metrics-config
  namespace: kafka
data:
  kafka-metrics-config.yml: |
    lowercaseOutputName: true
    rules:
      # Broker metrics
      - pattern: kafka.server<type=(.+), name=(.+), clientId=(.+), topic=(.+), partition=(.*)><>Value
        name: kafka_server_$1_$2
        type: GAUGE
        labels:
          clientId: "$3"
          topic: "$4"
          partition: "$5"
      # Messages in rate
      - pattern: kafka.server<type=BrokerTopicMetrics, name=MessagesInPerSec, topic=(.+)><>Count
        name: kafka_server_broker_topic_messages_in_total
        type: COUNTER
        labels:
          topic: "$1"
      # Consumer lag
      - pattern: kafka.consumer<type=consumer-fetch-manager-metrics, client-id=(.+)><>records-lag-max
        name: kafka_consumer_records_lag_max
        type: GAUGE
        labels:
          client_id: "$1"
      # Request rate
      - pattern: kafka.network<type=RequestMetrics, name=RequestsPerSec, request=(.+)><>Count
        name: kafka_network_requests_total
        type: COUNTER
        labels:
          request: "$1"
