apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: kafka-connect-metrics
  namespace: kafka
spec:
  selector:
    matchLabels:
      app: kafka-connect
  podMetricsEndpoints:
    - port: tcp-prometheus
      path: /metrics
      interval: 30s